# Generated by Django 2.1.15 on 2019-12-16 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('v', models.FloatField(blank=True, db_column='V', null=True)),
                ('i', models.FloatField(blank=True, db_column='I', null=True)),
            ],
            options={
                'verbose_name_plural': '基础数据表',
                'db_table': 'Base_Data',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('connectiontypeid', models.SmallIntegerField(blank=True, db_column='connectionTypeID', null=True)),
                ('nominalbasev', models.FloatField(blank=True, db_column='nominalBaseV', null=True)),
                ('levelV', models.FloatField(blank=True, db_column='levelV', null=True)),
                ('unitcode', models.CharField(blank=True, max_length=50, null=True)),
                ('stationid', models.IntegerField(blank=True, db_column='stationID', null=True)),
                ('shortcircuitcapacity', models.FloatField(blank=True, db_column='ShortCircuitCapacity', null=True)),
                ('tableid', models.BigIntegerField(blank=True, db_column='tableID', null=True)),
            ],
            options={
                'verbose_name_plural': '监测点表',
                'db_table': 'Site',
            },
        ),
        migrations.AddField(
            model_name='basedata',
            name='site',
            field=models.ForeignKey(db_column='Site_id', on_delete=django.db.models.deletion.CASCADE, related_name='Site_id', to='HarmonicSourceLocation.Site'),
        ),
        migrations.AlterUniqueTogether(
            name='basedata',
            unique_together={('site', 'id')},
        ),
    ]
