# Generated by Django 2.1.15 on 2019-12-25 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('stationid', models.IntegerField(db_column='StationID', primary_key=True, serialize=False)),
                ('stationname', models.CharField(db_column='StationName', max_length=200)),
                ('manager', models.CharField(blank=True, db_column='Manager', max_length=200, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=200, null=True)),
                ('telphone', models.CharField(blank=True, db_column='TelPhone', max_length=200, null=True)),
                ('descript', models.CharField(blank=True, db_column='Descript', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Station',
            },
        ),
    ]
