# Generated by Django 2.1.15 on 2019-12-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarmonicSourceLocation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='levelv',
        ),
        migrations.AddField(
            model_name='site',
            name='levelV',
            field=models.FloatField(blank=True, db_column='levelV', null=True),
        ),
    ]
